"""base

Revision ID: 1ca1b7228cee
Revises: 
Create Date: 2025-11-04 20:58:09.520480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ca1b7228cee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ferramenta',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('diaria', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DISPONIVEL', 'ALUGADA', name='statusferramenta'), nullable=False),
    sa.Column('categoria', sa.Enum('MANUAL', 'ELETRICA', 'PNEUMATICA', 'HIDRAULICA', 'MEDICAO', name='categoriaferramenta'), nullable=False),
    sa.Column('chave_pix', sa.Text(), nullable=False),
    sa.Column('avaliacao', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_avaliacoes', sa.Integer(), nullable=True),
    sa.Column('id_proprietario', sa.Integer(), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_proprietario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_solicitante', sa.Integer(), nullable=True),
    sa.Column('quantidade_dias', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_devolucao', sa.Date(), nullable=False),
    sa.Column('alugada', sa.Boolean(), nullable=False),
    sa.Column('pago', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_solicitante'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Foto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ferramenta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ferramenta'], ['ferramenta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ferramentas_pedido',
    sa.Column('id_ferramenta', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ferramenta'], ['ferramenta.id'], ),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id'], ),
    sa.PrimaryKeyConstraint('id_ferramenta', 'id_pedido')
    )
    op.create_table('historico_aluguel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['ferramenta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_carrinho',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_ferramenta', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ferramenta'], ['ferramenta.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_ferramenta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_carrinho')
    op.drop_table('historico_aluguel')
    op.drop_table('ferramentas_pedido')
    op.drop_table('Foto')
    op.drop_table('pedido')
    op.drop_table('ferramenta')
    op.drop_table('usuario')
    # ### end Alembic commands ###
