"""Ajusta autoincrement

Revision ID: 44ef747e9b53
Revises: 8dd1c26a289e
Create Date: 2025-08-08 11:52:44.622010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ef747e9b53'
down_revision: Union[str, Sequence[str], None] = '8dd1c26a289e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
