"""tabela de avaliacões_usuarios

Revision ID: 5605111777ea
Revises: cd740e2bcc98
Create Date: 2025-11-06 10:12:13.234391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5605111777ea'
down_revision: Union[str, Sequence[str], None] = 'cd740e2bcc98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacao_usuario_ferramenta',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_produto', sa.Integer(), nullable=False),
    sa.Column('avaliacao', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['ferramenta.id'], ),
    sa.PrimaryKeyConstraint('id_cliente', 'id_produto')
    )
    op.drop_constraint(op.f('Foto_id_ferramenta_fkey'), 'Foto', type_='foreignkey')
    op.create_foreign_key(None, 'Foto', 'ferramenta', ['id_ferramenta'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Foto', type_='foreignkey')
    op.create_foreign_key(op.f('Foto_id_ferramenta_fkey'), 'Foto', 'ferramenta', ['id_ferramenta'], ['id'])
    op.drop_table('avaliacao_usuario_ferramenta')
    # ### end Alembic commands ###
