"""Arruma nome de id_proprietario

Revision ID: 5b30f7a085f4
Revises: c38298f5262a
Create Date: 2025-08-08 11:42:41.758048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b30f7a085f4'
down_revision: Union[str, Sequence[str], None] = 'c38298f5262a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ferramenta', sa.Column('id_proprietario', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('ferramenta_id_propietario_fkey'), 'ferramenta', type_='foreignkey')
    op.create_foreign_key(None, 'ferramenta', 'usuario', ['id_proprietario'], ['id'])
    op.drop_column('ferramenta', 'id_propietario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ferramenta', sa.Column('id_propietario', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ferramenta', type_='foreignkey')
    op.create_foreign_key(op.f('ferramenta_id_propietario_fkey'), 'ferramenta', 'usuario', ['id_propietario'], ['id'])
    op.drop_column('ferramenta', 'id_proprietario')
    # ### end Alembic commands ###
