"""nova coluna de quantidade_estoque em ferramenta

Revision ID: 8c4b882b29e4
Revises: 65661a6eeede
Create Date: 2025-09-05 15:32:36.522405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c4b882b29e4'
down_revision: Union[str, Sequence[str], None] = '65661a6eeede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ferramenta', sa.Column('quantidade_estoque', sa.Integer()))
    op.drop_column('item_carrinho', 'quantidade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_carrinho', sa.Column('quantidade', sa.INTEGER(), autoincrement=False))
    op.drop_column('ferramenta', 'quantidade_estoque')
    # ### end Alembic commands ###
