"""Ajusta default de avaliacoes

Revision ID: 8dd1c26a289e
Revises: 5b30f7a085f4
Create Date: 2025-08-08 11:51:34.853573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dd1c26a289e'
down_revision: Union[str, Sequence[str], None] = '5b30f7a085f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ferramenta', 'quantidade_avaliacoes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ferramenta', 'quantidade_avaliacoes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
