"""Estado em usuario

Revision ID: c38298f5262a
Revises: a2b28ff4e38f
Create Date: 2025-08-08 11:37:31.354914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c38298f5262a'
down_revision: Union[str, Sequence[str], None] = 'a2b28ff4e38f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('estado', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'estado')
    # ### end Alembic commands ###
