"""empty message

Revision ID: cd5ad0eb1ac6
Revises: 8c4b882b29e4
Create Date: 2025-09-05 19:20:51.777669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5ad0eb1ac6'
down_revision: Union[str, Sequence[str], None] = '8c4b882b29e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ferramenta', sa.Column('ativo', sa.Boolean(), nullable=False))
    op.alter_column('ferramenta', 'quantidade_estoque',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ferramenta', 'quantidade_estoque',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('ferramenta', 'ativo')
    # ### end Alembic commands ###
