"""nome do arquivo em fotos

Revision ID: cd740e2bcc98
Revises: b9cd537da8ed
Create Date: 2025-11-04 21:22:42.872670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd740e2bcc98'
down_revision: Union[str, Sequence[str], None] = 'b9cd537da8ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Foto', sa.Column('nome_arquivo', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Foto', 'nome_arquivo')
    # ### end Alembic commands ###
