"""empty message

Revision ID: d3b629e45030
Revises: e0e84d69f492
Create Date: 2025-09-04 16:39:07.824729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b629e45030'
down_revision: Union[str, Sequence[str], None] = 'e0e84d69f492'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_carrinho',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_ferramenta', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_ferramenta'], ['ferramenta.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_ferramenta')
    )
    op.drop_table('carrinho')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrinho',
    sa.Column('id_cliente', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_pedido', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuario.id'], name=op.f('carrinho_id_cliente_fkey')),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id'], name=op.f('carrinho_id_pedido_fkey')),
    sa.PrimaryKeyConstraint('id_cliente', 'id_pedido', name=op.f('carrinho_pkey'))
    )
    op.drop_table('item_carrinho')
    # ### end Alembic commands ###
