"""Status de exclusão em ferramenta

Revision ID: edccd19fbc0b
Revises: 8c4b882b29e4
Create Date: 2025-09-18 13:17:31.723682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edccd19fbc0b'
down_revision: Union[str, Sequence[str], None] = '8c4b882b29e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ferramenta', 'quantidade_estoque',
               existing_type=sa.INTEGER())
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ferramenta', 'quantidade_estoque',
               existing_type=sa.INTEGER())
    # ### end Alembic commands ###
